CREATE TABLE tbl_LabTest
(LabReportNo varchar(4) constraint lab_PK primary key,
ldate varchar(30) default null,
receipt char(4)  not null references tbl_Prescription(receipt),
group1 varchar(30) default null,
group2 varchar(30) default null,
group3 varchar(30) default null,
group4 varchar(30) default null,
group5 varchar(30) default null,
labtest1 varchar(20) default null,
labtest2 varchar(20) default null,
labtest3 varchar(20) default null,
labtest4 varchar(20) default null,
labtest5 varchar(20) default null,
charge1 varchar(10) default null,
charge2 varchar(10) default null,
charge3 varchar(10) default null,
charge4 varchar(10) default null,
charge5 varchar(10) default null,
total1 varchar(10) default null,
total2 varchar(10) default null,
total3 varchar(10) default null,
total4 varchar(10) default null,
total5 varchar(10) default null,
result1 varchar(13) default null,
result2 varchar(13) default null,
result3 varchar(13) default null,
result4 varchar(13) default null,
result5 varchar(13) default null,
status varchar(8) default null,
refno char(4) default null
);