CREATE TABLE tbl_PbasicDetail
(pno char(4) constraint pbd_PK primary key,
pname varchar(20) constraint pbd_nm_nn not null,
pfathername varchar(20) constraint pbd_fnm_nn not null,
pdob char(10) constraint pbd_dob_nn not null,
page int  constraint pbd_age_nn_chk check (page>0) not null,
pgen char(1) constraint pbd_gen_nn_chk check (pgen='M' OR pgen='F') not null,
pms char(1) constraint pbd_ms_nn_chk check (pms='M' OR pms='U') not null,
pbloodg char(3) default null,
preligion char(9) default null,
presadd varchar(100) constraint pbd_radd_nn not null,
pperadd varchar(100) constraint pbd_padd_nn not null,
pdoorno int default null,
pstreet varchar(20) constraint pbd_street_nn not null,
ptown varchar(20) default null,
ppo varchar(20) default null,
ptaluk varchar(20) default null,
pdistrict varchar(20) constraint pbd_dist_nn not null,
pstate varchar(20) constraint pbd_state_nn not null,
pcountry char(5) constraint pbd_cou_nn not null,
ppincode number(10) default null,
pmobile number(10) constraint pbd_mob_nn not null,
pallergy varchar(25) default null,
pimg varchar(50) default null,
status char(8) default null,
refno char(4)  default null
);