CREATE TABLE tbl_Prescription
(receipt char(4) constraint r_PK primary key,
rdate varchar(30) constraint r_date_nn not null,
pno char(4) not null references tbl_PbasicDetail(pno),
name varchar(20) constraint r_nm_nn not null,
dob char(10) constraint r_dob_nn not null,
peradd varchar(100) constraint r_add_nn not null,
Disease varchar(20) constraint r_disease_nn not null,
medicine1 varchar(30) default null,
medicine2 varchar(30) default null,
medicine3 varchar(30) default null,
medicine4 varchar(30) default null,
medicine5 varchar(30) default null,
medicine6 varchar(30) default null,
labtest1 varchar(20) default null,
labtest2 varchar(20) default null,
labtest3 varchar(20) default null,
labtest4 varchar(20) default null,
labtest5 varchar(20) default null,
fee number(5,2)  constraint r_fee_nn not null,
doctorname varchar(20) constraint r_dnm_nn not null,
status varchar(8) default null,
labtest char(1) default null,
refno char(4) default null,
servicenm char(28) default null
);