CREATE TABLE tbl_Treatment
(billno char(4) constraint treat_bill_PK primary key,
ipd char(4) not null references tbl_Registration(ipd),
UHID char(4)  not null references tbl_Decision(UHID),
pno char(4)  not null references tbl_PbasicDetail(pno),
receiptno char(4)  not null references tbl_WardServices(receiptno),
pnm varchar(20) not null,
pfnm varchar(20) not null,
page int  not null,
psex char(1) not null,
Address varchar(100) not null,
mobile number(10) not null,
service varchar(28) not null,
roomtype varchar(19) not null,
roomno varchar(5) not null,
Ptype varchar(10) not null,
bednumber int not null,
price number(6,2) not null,
admissiondate varchar(30) not null,
LabReportNo char(4) default null ,
refno char(4) default null,
Abill1 char(4) constraint treat_abill1_nn not null,
Adate1 varchar(10) constraint treat_adate1_nn not null,
Aamount1 number(6,2) constraint treat_aamount1_nn not null,
Abill2 char(4) constraint treat_abill2_nn not null,
Adate2 varchar(10) constraint treat_adate2_nn not null,
Aamount2 number(10,2) constraint treat_aamount2_nn not null,
slno char(4) constraint treat_slno_nn not null,
visited_Dr1_nm varchar(20) default null,
dr1_billdate varchar(10) default null,
dr1_charge number(6,2) default null,
dr1_visit_times int default null,
dtotal1 number(10,2) default null,
visited_Dr2_nm varchar(20) default null,
dr2_billdate varchar(10) default null,
dr2_charge number(6,2) default null,
dr2_visit_times int default null,
dtotal2 number(10,2) default null,
Operation_Charge number(10,2) constraint treat_ocharge2_nn not null,
Nurshing_Charge number(6,2) constraint treat_ncharge2_nn not null,
status char(4) constraint treat_status_nn not null
);

